#!/usr/bin/env python

import qsa2python as q2p
from optparse import OptionParser

def main():

    parser = OptionParser()
    parser.set_defaults(
        quiet=False,
        verbose=False,
        )
        
    parser.add_option("-v", help="Be more verbose"
                        ,dest="verbose", action="store_true")
                        
    parser.add_option("-q", help="Quiet. Produce less output."
                        ,dest="quiet", action="store_true")

    (options, args) = parser.parse_args()



    
if __name__ == "__main__":
    main()
